### ISSUE TITLE
Build for OSX

### ISSUE THREAD

**Issue by rodneyrod** [PurpleI2P/i2pdbrowser#1]

**Comment by orignal** [comment]
what's wrong with it now?

**Comment by r4sas** [comment]
@faxboss, can we close that issue?

**Comment by rodneyrod** [comment]
@r4sas There still haven't been any OSX builds put on the releases page, I wouldn't close this issue until that happens.

**Comment by r4sas** [comment]
@rodneyrod kk. I'll wait @faxboss to do some things and update to last i2pd.

**Comment by r4sas** [comment]
@rodneyrod can you test osx builder from 1.2.6 branch osx folder?
https://github.com/PurpleI2P/i2pdbrowser/tree/1.2.6/osx

**Comment by r4sas** [comment]
Build scripts released. Awaiting for reports.
