### ISSUE TITLE
NoScript not compatible

### ISSUE THREAD

**Issue by faxboss** [PurpleI2P/i2pdbrowser#14]
At the 20th November, NoScript fully ported to WebExtensions. 
To my understanding, this means it is no longer compatible with Firefox ESR.

If I run the build script, for Linux, I get the following console warning:
`addons.xpi	WARN	Add-on {73a6fe31-595d-460b-a920-fcc0f8843232} is not compatible with application version.`

I have made a PR #12  as possible workaround, which will install NoScript v. [5.1.7](https://noscript.net/getit). This is still compatible with Firefox ESR.

I am not entirely sure this is the right way to handle it.

**Comment by r4sas** [comment]
Merged
