### ISSUE TITLE
Consistent naming

### ISSUE THREAD

**Issue by ghost** [PurpleI2P/i2pdbrowser#19]
I know that it may sound silly to some people, but I really think there should be consistent naming.

On the i2pd wiki, this browser bundle is called "I2PdBrowserPortable", but the repository is called something else. Different naming is used throughout the build scripts too, etc. Could we establish an agreed upon name?

**Comment by l-n-s** [comment]
I guess we could stick to "I2P Browser Bundle", portability is sorta implicit.

**Comment by r4sas** [comment]
s/I2P/I2Pd/e

**Comment by l-n-s** [comment]
I2P is easier to remember than I2Pd -- and there is no java bundle anyway. But still "I2P" is hard to spell... Probably, something like "Invisible Browser Bundle"?

**Comment by r4sas** [comment]
i2b :D
