### ISSUE TITLE
Tor Browser instead of Firefox ESR

### ISSUE THREAD

**Issue by nomatterwat** [PurpleI2P/i2pdbrowser#21]
Why not use Tor Browser [0] instead of plain Firefox? It is designed for the privacy and is much more reliable out of the box. If you expect that people would use your browser for privacy-critical tasks, consider this.

[0] https://www.torproject.org/projects/torbrowser.html.en

**Comment by za3ter2p** [comment]
I2P-Java has now [beta versions](https://geti2p.net/en/download/lab) of forked TBB , so wouldnt be easy to just change proxy settings with some bookmarks or so (minor changes) and making it i2pdbrowser based on TBB ? 

cc @r4sas @orignal @majestrate

**Comment by r4sas** [comment]
Problem is building, because required big amount of resources (at least 40 GB, CPU, RAM).
