### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by smaragdus** [PurpleI2P/i2pdbrowser#23]
**i2pdbrowser** version [1.2.7](https://github.com/PurpleI2P/i2pdbrowser/releases/tag/1.2.7) (bundled with **i2pd** version [2.19](https://github.com/PurpleI2P/i2pd/releases/tag/2.19.0)) cannot initiate due to a runtime error.

 **error message:**

```
This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
```

**screens:**

![i2pdbrowser 1 2 7 0 - 2018-11-20 - error - 001](https://user-images.githubusercontent.com/9025757/48802196-207e9f00-ed17-11e8-868d-5be53ade6665.png)

![i2pdbrowser 1 2 7 0 - 2018-11-20 - error - 002](https://user-images.githubusercontent.com/9025757/48802205-2d02f780-ed17-11e8-8780-ef512401e689.png)

This happens under _Windows 8 x64_.

Updating **i2pd** to version [2.22](https://github.com/PurpleI2P/i2pd/releases/tag/2.22.0) did not help either, the error persisted.

**Comment by r4sas** [comment]
Did you use original system, not modified by someone?
Win 8 or 8.1? I dont know how it will work on win 8. Please show `winver` command window.

**Comment by smaragdus** [comment]
@r4sas 

> Did you use original system, not modified by someone?

I do not understand what you mean. I tried to use **i2pdbrowser** version **1.2.7** without any modifications.

> Win 8 or 8.1?

I said **Windows 8 x64** in my first post.

> I dont know how it will work on win 8. Please show `winver` command window.

See it below:

![snipaste-2018-11-21_082317](https://user-images.githubusercontent.com/9025757/48822951-94489800-ed67-11e8-930a-5a6e4e03b98b.png)

I found a post about similar problem- please see [here](https://github.com/PurpleI2P/i2pd/issues/871#issuecomment-336699973).

**Comment by smaragdus** [comment]
@r4sas 

First, thanks for taking your time to investigate the problem.

> I'm about Windows itself.
> Often problems because used patched or modified system.

Nothing very special about my system- UAC disabled, updates disabled. I rarely see such errors (in most cases errors with .NET).

> Lemme check in VBox with clean system.

Thank you. It might be that my system is faulty.

> btw, better move that issue to i2pd repo, because i2pdbrowser repo is wrong place.

What exactly should I do? Close this issue and open a new one [here](https://github.com/PurpleI2P/i2pd/issues)?

**Comment by r4sas** [comment]
Tested in VBox on clean system.

![image](https://user-images.githubusercontent.com/7023612/48836124-ebb02d80-ed92-11e8-8c71-177448db44dd.png)

All works correclty. So you need check it out what happens in your system.

**Comment by r4sas** [comment]
>What exactly should I do? Close this issue and open a new one here?

Really, I dont want get in touch with cracked/modified/broken systems, because in that case reason only one - someone who build that system image removed from it something what required for correct work.

If you installed system not from original MSDN image, or, not got it preinstalled with your computer, in that case I really cannot do anything.

**Comment by orignal** [comment]
I suspect it crashes because username is Yo :)
Seriously, please check if it has write access to that folder and it's not prevented by an anitivirus or  something.

**Comment by orignal** [comment]
What do you see inside i2pd folder, like router.keys, router.info, netdb, etc.?

**Comment by orignal** [comment]
I don't see neither i2pd.log, no ntcp2.keys. Seems you system is not able to create them

**Comment by r4sas** [comment]
Because here is 2.19.

**Comment by r4sas** [comment]
Okay, lets go other way:
Download "Dependency Walker" (http://dependencywalker.com/) and make dependency image.

* Download app
* Unpack and run it
* File -> Open -> i2pd.exe 
* Let program analyze dependencies
* Save dependencies image (File -> Save )
* Compress output file and post it here.

**Comment by smaragdus** [comment]
@r4sas & @orignal 

Thank you for your help!
I also tried **i2pd_2.22.0_win32_mingw.zip** & **i2pd_2.22.0_win64_mingw.zip**, the I used the installer- **setup_i2pd_v2.22.0.exe**. This is what I saw in AppData (C:\Users\Yo\AppData\Roaming\i2pd):

 **screen:**

![1snipaste-2018-11-21_175134](https://user-images.githubusercontent.com/9025757/48852697-9554e600-edb6-11e8-9eb8-a1b4e40a6b76.png)

**html:**
[i2pd.zip](https://github.com/PurpleI2P/i2pdbrowser/files/2604887/i2pd.zip)

The program tries to load in system tray:

![sshot-2018-11-21- 17-48-49](https://user-images.githubusercontent.com/9025757/48852924-12805b00-edb7-11e8-90ca-ec3139e8cf67.png)

I can even access tray commands for a short period of time:

![snipaste-2018-11-21_174942](https://user-images.githubusercontent.com/9025757/48852976-2af07580-edb7-11e8-81b0-ecc9cf21b89f.png)

Then it crashes again.

**Comment by smaragdus** [comment]
I saved the analysis of **Dependency Walker**- **i2pd.dwi** and dressed it up in zip, please find it below:

**i2pd.dwi:**
[i2pd.zip](https://github.com/PurpleI2P/i2pdbrowser/files/2604927/i2pd.zip)

**screen:**
![snipaste-2018-11-21_180736](https://user-images.githubusercontent.com/9025757/48853628-94bd4f00-edb8-11e8-9c0f-2b1559c8406f.png)

I am absolutely sure that the problem is within my system.

**Comment by orignal** [comment]
I want you to try in another folder. And better if you try just i2pd, not browser

**Comment by r4sas** [comment]
@smaragdus can you run i2pd inside Dependency Walker?
Open in program i2pd.exe and run it in Profile -> Start profiling.

Lets see what can say profiler.

**Comment by smaragdus** [comment]
@orignal 

> I want you to try in another folder. And better if you try just i2pd, not browser

I did that several times using these builds:

- i2pd_2.22.0_win32_mingw.zip
- i2pd_2.22.0_win64_mingw.zip

I got the same result. I even deleted i2pd folder from AppData before testing x32 and x64 builds anew.

@r4sas 

> can you run i2pd inside Dependency Walker?
> Open in program i2pd.exe and run it in Profile -> Start profiling.
> 
> Lets see what can say profiler. Dont change any checkbox, start with default.

I did what you suggested. Results:

**screen:**

![snipaste-2018-11-22_000336](https://user-images.githubusercontent.com/9025757/48870910-3f4e6580-edeb-11e8-91dd-a051b9ce43d7.png)

**analysis:**

[i2pd.zip](https://github.com/PurpleI2P/i2pdbrowser/files/2605955/i2pd.zip)

Guys, obviously my system is faulty. I wasted too much time of yours so now I feel really uneasy. Thank you very much for your efforts to help me, I appreciate it a lot!

**Comment by r4sas** [comment]
I think I know where can be problem.

```
LoadLibraryA("ZLIB1.dll") called from "I2PD.EXE" at address 0x0000000000549F67.
Loaded "ZLIB1.DLL" at address 0x000007FBAF540000.  Successfully hooked module.
DllMain(0x000007FBAF540000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "ZLIB1.DLL" called.
DllMain(0x000007FBAF540000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "ZLIB1.DLL" returned 1 (0x1).
LoadLibraryA("ZLIB1.dll") returned 0x000007FBAF540000.
```

It mustn't load it from outside, but why it loaded from `c:\program files\intel\wifi\bin\ZLIB1.DLL` on your system I really dont know.

Try place zlib1.dll from archive near i2pd.exe.
[zlib1.zip](https://github.com/PurpleI2P/i2pdbrowser/files/2608164/zlib1.zip)

Second: wtf is this?
```
Loaded "DSTUDIOLSP64.DLL" at address 0x0000000180000000.  Successfully hooked module.
DllMain(0x0000000180000000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "DSTUDIOLSP64.DLL" called.
Loaded "SMARTSYSTEMMENUHOOK64.DLL" at address 0x000007FBBF940000.  Successfully hooked module.
DllMain(0x000007FBBF940000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "SMARTSYSTEMMENUHOOK64.DLL" called.
DllMain(0x000007FBBF940000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "SMARTSYSTEMMENUHOOK64.DLL" returned 1 (0x1).
Loaded "AM64-34121.DLL" at address 0x0000000002470000.  Successfully hooked module.
DllMain(0x0000000002470000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "AM64-34121.DLL" called.
```

Points to `c:\program files (x86)\downloadstudio\plugins\DSTUDIOLSP64.DLL`, `c:\portable programs\smartsystemmenu\SMARTSYSTEMMENUHOOK64.DLL`, `c:\program files (x86)\ad muncher\AM64-34121.DLL` and
