### ISSUE TITLE
A non-necessary error message?

### ISSUE THREAD

**Issue by nonlinear-chaos** [PurpleI2P/i2pdbrowser#24]
```
i2pdbrowser/build$ ./build 

[...]
rm: cannot delete '../app/run-mozilla.sh': No such file or directory
[...]
```
why print this? it's only needed to check whether the file exists, and to not rm it if it doesn't exist

**Comment by r4sas** [comment]
It was in 5X versions.

**Comment by nonlinear-chaos** [comment]
@r4sas please close the issue if not relevant to last stable version

**Comment by r4sas** [comment]
1.2.8 released.
