### ISSUE TITLE
Settings for i2pdbrowser with a ssh (raspberry) router

### ISSUE THREAD

**Issue by l8i** [PurpleI2P/i2pdbrowser#25]
First at all, **thanks for all your work and all your time you spend for i2pd!**

My issue:
I did not get my setup: raspberry i2pd router - shh - i2pdbrowser running.
Is it mandatory to have the i2pd installation on the same machine when running this script?
If not is it only the proxy setting I have to adapt?

Remark:
- i2pd on raspberry works (used i2pd-setup from i2pberry)
- raspberry shh connection works

**Comment by r4sas** [comment]
> Is it mandatory to have the i2pd installation on the same machine when running this script?

Only link-local connections, that inside your OS is counted as secure.

> If not is it only the proxy setting I have to adapt?

Use default settings, but add port forwarding in your SSH connection from PC where you wish run modded firefox (run it from Firefox directory directly by running FirefoxPortable.exe) to raspberry where i2pd is installed.
How to configure port forwarding please read in internet.
