### ISSUE TITLE
Make a special i2pdbrowser icon for Desktop app shortcuts etc

### ISSUE THREAD

**Issue by nonlinear-chaos-order-etc** [PurpleI2P/i2pdbrowser#27]
Icons for i2pd_qt and i2pdbrowser should differ (be different between each other).

**Comment by r4sas** [comment]
Так тут разные иконки. У браузера основная иконка без перьев вокруг.

**Comment by nonlinear-chaos-order-etc** [comment]
@r4sas а скинь иконку браузера? чот я не нашёл с 1-2 тыка

**Comment by r4sas** [comment]
> @r4sas а скинь иконку браузера? чот я не нашёл с 1-2 тыка

https://github.com/PurpleI2P/i2pdbrowser/blob/master/windows_prebuilt/src/browser.ico

**Comment by nonlinear-chaos-order-etc** [comment]
да, я уже догадался по .ext поискать и тоже нашёл. пасиб!
