### ISSUE TITLE
when running ./i2pd i get the error message "Can't find 'screen' installed. That script needs it!" even though it is installed

### ISSUE THREAD

**Issue by elypter** [PurpleI2P/i2pdbrowser#3]

**Comment by orignal** [comment]
what script are you talking about?

**Comment by r4sas** [comment]
@orignal he's about check [here](https://github.com/PurpleI2P/i2pdbrowser/blob/master/linux/i2pd/i2pd#L12). I ckecked other variable :D
@elypter tnx, fix it.
