### ISSUE TITLE
Erase all history on exit

### ISSUE THREAD

**Issue by H5117** [PurpleI2P/i2pdbrowser#35]
Why is not the private mode activated by default?

**Comment by r4sas** [comment]
You can enable it yourself.

**Comment by H5117** [comment]
I thought this browser is intended for browsing i2p anonymously, like Tor browser is user for Tor. Am I wrong?
If so, what browser should I use to browse i2p anonymously (without providing [fingerprints](https://ssd.eff.org/en/module/what-fingerprinting) to servers)?

**Comment by r4sas** [comment]
Most fingerprints stripped by http proxy and noscript extension.

**Comment by H5117** [comment]
What about SOCKS5 proxy? Is it safe to use?
Also is it safe to use regular Firefox with noscript extension?
I think the i2pd team should describe such critical for anonymity things in the docs, because it is not self-evident for regular users like me. But in any case, thank you for help.
