### ISSUE TITLE
[windows; defect(?)] with port 7070 

### ISSUE THREAD

**Issue by nonlin-lin-chaos-order-etc-etal** [PurpleI2P/i2pdbrowser#36]
Schrab, [21.01.2022 20:39]

он у меня не хочет коннектиться в последнее время

Markandeya 𒀭𒄑𒉋𒂵𒈨𒌋𒌋𒌋 🐡 SHARDAHC45*, [22.01.2022 01:18]

оч важно чтоб твои часы казали максимально точное время

ну и когда браузер запущен открой в любом браузере http://127.0.0.1:7070/

```
<eternalchaoticexplosion> R4SAS, в и2пд браузере 7070 создается?
<eternalchaoticexplosion> или отключён?
<R4SAS> eternalchaoticexplosion: всм
<eternalchaoticexplosion> ну вебконсоль там пашет или нет?
<eternalchaoticexplosion> и2пд
<R4SAS> пашет
<eternalchaoticexplosion> ок так и передам пасиб!
```

scr shot 1:

![изображение](https://user-images.githubusercontent.com/19966907/150574336-6b3947eb-afbf-4112-83f3-5bf6066e9c8f.png)

Schrab, [22.01.2022 01:32]

Причем он у меня в первый день запустился нормально, я там полазил даже

scr shot 2:

![изображение](https://user-images.githubusercontent.com/19966907/150574422-012622ef-7bdd-4b5d-b9fa-c963ea9afef7.png)

Markandeya 𒀭𒄑𒉋𒂵𒈨𒌋𒌋𒌋 🐡 SHARDAHC45*, [22.01.2022 01:33]

эт какая винда?

Schrab, [22.01.2022 01:33]

W10 x64

21H2

Markandeya 𒀭𒄑𒉋𒂵𒈨𒌋𒌋𒌋 🐡 SHARDAHC45*, [22.01.2022 01:34]

скину иссуй в багтрекер мож кто виндой занимается. все там линухойды из девелуперов, иногда виндозники помогают

Schrab, [22.01.2022 01:35]

ага

**Comment by r4sas** [comment]
У него небось стоит AnyDesk.

**Comment by nonlin-lin-chaos-order-etc-etal** [comment]
Markandeya 𒀭𒄑𒉋𒂵𒈨𒌋𒌋𒌋 🐡 SHARDAHC45*, [22.01.2022 02:06]

```
<R4SAS> eternalchaoticexplosion: У него небось стоит AnyDesk.
<R4SAS> он по дуфолту юзает 7070
```

 Markandeya 𒀭𒄑𒉋𒂵𒈨𒌋𒌋𒌋 🐡 SHARDAHC45*, [22.01.2022 02:06]

подтверждаю, юзает энидэск

Markandeya 𒀭𒄑𒉋𒂵𒈨𒌋𒌋𒌋 🐡 SHARDAHC45*, [22.01.2022 02:06]

7070 порт. закрой временно энидеск и перезапусти и2пд браузер

Schrab [22.01.2022 02:28]

принял! энидеск стоит, да

 Markandeya 𒀭𒄑𒉋𒂵𒈨𒌋𒌋𒌋 🐡 SHARDAHC45*, [22.01.2022 02:40]

ну вот закрывай его или и2пд_браузер конфиг i2pd.conf исправь порт хттп вебконсколи

**Comment by schrab** [comment]
Вырубил Anydesk - всё заработало.
