### ISSUE TITLE
Noscript is blocking base32 script

### ISSUE THREAD

**Issue by halorx** [PurpleI2P/i2pdbrowser#41]
Should it be allowed globally? What does it mean?

**Comment by r4sas** [comment]
That is default NoScript's behavior, so I won't change anything.

**Comment by halorx** [comment]
Doesn't it break security? Because of broken base32 end to end authentication, caused by noscript blocking it? Or i am misunderstanding something?

**Comment by r4sas** [comment]
Please provide useful example.

**Comment by halorx** [comment]
What do you mean with that? Sry I'm just a user but im worried about it because the private key from hidden service is encoded as a signature in the public base32 address to provide end to end authentication property just like in TOR, so if it may not checks it correctly it might be dangerous if the browser may breaks this security feature.

**Comment by r4sas** [comment]
This is not related to JS and NoScript. `base32` address is checked cryptographically inside I2P/i2pd client.

**Comment by halorx** [comment]
Thank you for your fast answer! Also i mixed everything up before, so sry. My answer that i have before was not correct.
