### ISSUE TITLE
How to stop i2pd?

### ISSUE THREAD

**Issue by stefan-reich** [PurpleI2P/i2pdbrowser#44]
How can I stop i2pd in PurpleI2P? Ideally, maybe the browser could suggest stopping the daemon when you close the window?

Also, how can I see the i2pd stats page in the bundled browser? (On that page I assume I then could stop i2pd cleanly too.)

**Comment by r4sas** [comment]
Open `http://127.0.0.1:7070/` -> Router commands -> Start graceful shutdown.

As I remember, there is webconsole item on speed dial page (new tab).

**Comment by stefan-reich** [comment]
@r4sas Thanks, both things you said are correct. I still think this should be made easier for users though.

**Comment by r4sas** [comment]
If you can do something about this idea then you can open a PR with suggested changes to the browser bundle.
