### ISSUE TITLE
Rename window title?

### ISSUE THREAD

**Issue by stefan-reich** [PurpleI2P/i2pdbrowser#45]
Right now, every browser window is simply called "Mozilla Firefox". Essentially you have to look twice to see whether it's a normal Firefox or PurpleI2P. Is there a way to rename that?

**Comment by r4sas** [comment]
Build browser from sources. But no one will do it.

**Comment by stefan-reich** [comment]
> Build browser from sources. But no one will do it.

Ok, so you download the Firefox binary as-is without compiling it yourself, and that makes changing the browser harder. Did I get it right? I'm not personally in the know about how configurable Firefox is in binary form.

**Comment by r4sas** [comment]
Yes. All I can do is change only some options using `policy.json` and applied by autoconfig changes to internal options provided by developers. Application name is hardcoded inside binaries.
