### ISSUE TITLE
%xOS% in Win7

### ISSUE THREAD

**Issue by 40OIL** [PurpleI2P/i2pdbrowser#46]
download addresses look like this:
https://ftp.mozilla.org/pub/firefox/releases/102.3.0esr/win64/ru/Firefox%20Setup%20102.3.0esr.exe
and
https://github.com/PurpleI2P/i2pd/releases/download/2.43.0/i2pd_2.43.0_win64_mingw.zip

but %xOS% == "x64" in Win7 x64, not "win64"

**Comment by r4sas** [comment]
https://github.com/PurpleI2P/i2pdbrowser/blob/2bbd66f0db475329ce86d2d55761e6b73c8cdb5b/windows/build/build.cmd#L167-L170

**Comment by r4sas** [comment]
@40OIL thanks for pointing out the problem.

**Comment by 40OIL** [comment]
this check is wrong ))
I have despite the fact that PROCESSOR_ARCHITECTURE=x86 the system is still x64
(see pic https://www.dropbox.com/s/o0socoskm40eiwg/win7_x64.png?dl=0)

in my environment variables:
PROCESSOR_ARCHITECTURE=x86
PROCESSOR_ARCHITEW6432=AMD64

I found these checks that work better:
IF EXIST "%PROGRAMFILES(X86)%" (GOTO 64BIT) ELSE (GOTO 32BIT)
or
Set xOS=x64
If "%PROCESSOR_ARCHITECTURE%"=="x86" If Not Defined PROCESSOR_ARCHITEW6432 Set xOS=x86
or
set xOS=win86
if DEFINED ProgramFiles(x86) set xOS=win64


probably best to use
systeminfo | find /i "based"
or
wmic os get OSArchitecture
only there it will be necessary to parse the output

**Comment by r4sas** [comment]
Nope, everything correct now.
1. Set win32 by default
2. Check if PROCESSOR_ARCHITEW6432 is defined and set win64
3. Check if PROCESSOR_ARCHITECTURE != x86 and set win64

**Comment by r4sas** [comment]
Еще раз, специально, для недогоняющих:

![image](https://user-images.githubusercontent.com/7023612/203492428-2d574679-25b2-4d51-8a32-f652a46f784f.png)

https://github.com/PurpleI2P/i2pdbrowser/commit/ce06fc8cf62365e5b091fd4c969f85fe0c863716#diff-7dbe70c0916a6b9be11a7e8d6eb01d8fb7056171667dc97d28e4542d5287ee85R169

По поводу языка - берется язык системы. Переделывать не буду, поскольку на случай необходимости русский язык все равно устанавливается в браузер сразу же.
