### ISSUE TITLE
Non-Russian Bookmarks

### ISSUE THREAD

**Issue by SentToDevNull** [PurpleI2P/i2pdbrowser#5]
I love the concept of providing a pre-configured browser that works with i2pd out of the box, but almost all the default bookmarks as of right now lead to Russian sites. It would be very helpful to include links to popular eepsites in other languages such as English, German, etc. so that new users of any language have a place to start.

**Comment by l-n-s** [comment]
I like the idea. We need someone to collect and maintain that list of websites tho.

**Comment by orignal** [comment]
@l-n-s  where should we collect them?

**Comment by r4sas** [comment]
@SentToDevNull We think about that.
If you want to help, you can offer eepsites owners to add request [here](http://333.i2p/topics/21)
