### ISSUE TITLE
problem with mac m1

### ISSUE THREAD

**Issue by Jessy-Ding** [PurpleI2P/i2pdbrowser#53]
Hi, when I try to run the Firefox by executing `./i2pdbrowser-portable`:
It shows: UNSUPPORTED (log once): POSSIBLE ISSUE: unit 1 GLD_TEXTURE_INDEX_2D is unloadable and bound to sampler type (Float) - using zero texture because texture unloadable
and the browser said the proxy server is refusing connections:
<img width="648" alt="image" src="https://user-images.githubusercontent.com/89423283/206917676-b56f99a9-bd6d-4b32-b087-5526a63cc6f3.png">
Could you pls help with this issue? thanks.

**Comment by r4sas** [comment]
1. Can't help with FF stuff on MacOS
2. You haven't started i2pd.
