### ISSUE TITLE
unable to use on my win 10 64 desktop

### ISSUE THREAD

**Issue by p060477** [PurpleI2P/i2pdbrowser#57]
i dl the 1.3.3 vers but everytime i start with admin right the .bat file it says that it did not find the firefoxportable.exe...why...??
is it a bug...??
thxs so much in adv 
cheers

**Comment by r4sas** [comment]
Which package are you downloading?

**Comment by r4sas** [comment]
I hope you extracted package before starting batch?

**Comment by p060477** [comment]
of course i extracted the package before...cause the .bat file is in the package...so how to execute it before...??

**Comment by p060477** [comment]
and also what about:
https://github.com/PurpleI2P/i2pd-qt
...is there a way to be able to easly have it on win 10 home 64...??

**Comment by p060477** [comment]
anyway unable to surf with yr browser...:

![Immagine](https://github.com/PurpleI2P/i2pdbrowser/assets/12773559/2ddf98ae-80d9-4ddc-9b65-ab2c7abe54a7)


any ideas...??

**Comment by r4sas** [comment]
1. Check if http://i2pd.i2p/ works. If it is, that can only mean that requested site is really offline. Detailed information about alive sites can be found on http://notbob.i2p/ or http://reg.i2p/.

**Comment by p060477** [comment]
hi, first thxs so much
i got this:

![Immagine](https://github.com/PurpleI2P/i2pdbrowser/assets/12773559/97a2abf5-81ee-4e7c-941a-2ae4d9e95283)


but how to simply want to see which is my ip address...??...

**Comment by p060477** [comment]
but how if i simply want to see which is my ip address...??...
and why the i2pd.exe process do not stop if i exit...??...i see it still running in task manager...
and the only way is to kill it manually...
is it a bug...??

**Comment by p060477** [comment]
but how if i simply want to see which is my ip address...??...
    and where we are able to find: ONLY I2P torrents and magnets....
    and why the i2pd.exe process do not stop if i exit...??...i see it still running in task manager...
    and the only way is to kill it manually...
    is it a bug...??

**Comment by r4sas** [comment]
1. There is no IP addresses.
2. http://tracker2.postman.i2p/
3. No. i2pd will stop after expiring of all transit tunnels. How do you stop it?

**Comment by p060477** [comment]
1) which is yr **search engine**...??...i mean a search engine , like google for example,  suitable with yr sw...??
2) in the tray bar icon of i2pd there is the option to shutdown gracelly or to exit...why in both cases the process
   remains active in task manager...??...all sw where you exit **should have to terminate their action in task manager...**

**Comment by p060477** [comment]
1) 
so now which is the search engine working in yr i2p browser?..i hope yr browser should have at least one working..isn't it..?

4)
i showed the bug in the right repository of XD...where you replied to past only magnet and torrent I2P urls in webui
so i'm asking here to the right person,the one who replied that, why this is not working at all, with the torrent's urls i specify, ...:
see the screenshoots just done:

![Immagine](https://github.com/PurpleI2P/i2pdbrowser/assets/12773559/b75347c9-173c-4a31-84e0-e174ff70f34a)

![Immagine2](https://github.com/PurpleI2P/i2pdbrowser/assets/12773559/396d6989-d92e-43b4-bcbd-ebebb7938647)


...but have you tried what you stated...??...

**Comment by p060477** [comment]
1) 
so now which is the search engine working in yr i2p browser?..i hope yr browser should have at least one working..isn't it..?

4)
i showed the bug in the right repository of XD...where you replied to past only magnet and torrent I2P urls in webui
so i'm asking here to the right person,the one who replied that, why this is not working at all, with the torrent's urls i specify, ...:
see the screenshoots just done:

![Immagine](https://github.com/PurpleI2P/i2pdbrowser/assets/12773559/b75347c9-173c-4a31-84e0-e174ff70f34a)

![Immagine2](https://github.com/PurpleI2P/i2pdbrowser/assets/12773559/396d6989-d92e-43b4-bcbd-ebebb7938647)

when i push the green botton on the right : "add"   in the webui
nothing happens:
`[NFO] 2023-11-14 20:56:00.7118568 +0100 CET m=+27.598771501     fetching torrent from http://tracker2.postman.i2p/index.php?action=Download&id=73305
[ERR] 2023-11-14 21:01:13.3621293 +0100 CET m=+340.249010401    failed to fetch torrent: Get "http://tracker2.postman.i2p/index.php?action=Download&id=73305": EOF
[NFO] 2023-11-14 21:01:56.5968622 +0100 CET m=+383.483739001    fetching torrent from http://tracker2.postman.i2p/index.php?action=Download&id=73305
[NFO] 2023-11-14 21:02:04.4372118 +0100 CET m=+391.324087801    fetching torrent from http://tracker2.postman.i2p/index.php?action=Download&id=73305
[ERR] 2023-11-14 21:07:02.6608121 +0100 CET m=+689.547658201    failed to fetch torrent: Get "http://tracker2.postman.i2p/index.php?action=Download&id=73305": EOF
[ERR] 2023-11-14 21:07:10.4985081 +0100 CET m=+697.385353501    failed to fetch torrent: Get "http://tracker2.postman.i2p/index.php?action=Download&id=73305": EOF
[NFO] 2023-11-14 21:21:30.0142494 +0100 CET m=+1556.901008801   fetching torrent from http://tracker2.postman.i2p/index.php?action=Download&id=73305
[ERR] 2023-11-14 21:26:36.5388222 +0100 CET m=+1863.425551001   failed to fetch torrent: Get "http://tracker2.postman.i2p/index.php?action=Download&id=73305": EOF`

only the magnet urls are managed and it is possible to add them with that green button in the webui
the torrent urls really no at all...have you tried...???.....


...i re-ask : but **have you tried** what you stated...??...

**Comment by r4sas** [comment]
ofc.
```
[NFO] <<edited>> m=+214.756876501    fetching torrent from http://tracker2.postman.i2p/index.php?action=Download&id=73357
[NFO] <<edited>> m=+219.888819601    checking local data for Your.Lucky.Day.2023.1080p.AMZN.WEBRip.1400MB.DD5.1.x264-GalaxyRG[TGx]
[WRN] <<edited>> m=+219.890915501    piece missmatch: 3b71f43ff30f4b15b5cd85dd9e95ebc7e84eb5a3 != 1dcfac4c917ab9ca52040577a6444fced88bf543
... <<metadata downloaded here>>
[WRN] <<edited>> m=+235.850994501    piece missmatch: db61296ef9a92cd0ca7dfd436ed2b6fb818dee40 != 043d5e3b935083e48ebdbdf097b0cb58f9c9ce52
[NFO] <<edited>> m=+235.851995101    local data check done for Your.Lucky.Day.2023.1080p.AMZN.WEBRip.1400MB.DD5.1.x264-GalaxyRG[TGx]
```

What you can try to do: open `torrents.ini` in XD directory, find `[i2p]` section and edit it to look like:

```ini
[i2p]
disabled=0
address=127.0.0.1:7656
inbound.quantity=5
outbound.quantity=5
inbound.length=2
outbound.length=2
i2cp.leaseSetType=3
i2cp.leaseSetEncType=4
```

**Comment by p060477** [comment]
hi, first thxs for yr reply
done 
now i make some tries and i will report to you if works or not
and what about the other question:

**which is the search engine working in yr i2p browser?..i hope yr browser should have at least one working..isn't it..?**

thxs for yr kind attn
cheers

**Comment by r4sas** [comment]
1. If legwork is dead, so there is no search engines publicly available.
2. Enable javascript for page. i2pdbrowser comes with noscript extension.

**Comment by p060477** [comment]
2. thxs now also webui is working fine!  **thxs again**
1. so if we are searching for i2p site to manage with the i2pdbrowser...?...how to...?
 thxs again for yr kind **and precious helping**
cheers
