### ISSUE TITLE
process i2pd.exe still running in task after exit...is it a BUG..??

### ISSUE THREAD

**Issue by p060477** [PurpleI2P/i2pdbrowser#58]
why the i2pd.exe process do not stop if i exit...??...i see it still running in task manager...
  and the only way is to kill it manually...  is it a bug...??

 and where we are able to find: ONLY I2P torrents and magnets....

  and how if i simply want to see which is my ip address...??...

**Comment by r4sas** [comment]
Stop creating tons of issues.
