### ISSUE TITLE
media.peerconnection.ice.proxy_only not being set by default?

### ISSUE THREAD

**Issue by MagicalDrizzle** [PurpleI2P/i2pdbrowser#59]
it seems like navigating to i2p sites won't work unless you set that config to `true`, and it's in the official I2P instructions also.

**Comment by r4sas** [comment]
Navigating?

**Comment by MagicalDrizzle** [comment]
just accessing I2P sites.

**Comment by MagicalDrizzle** [comment]
actually I was stupid and me toggling that setting just coincided with i2p actually loading up, my apologies
